### ISSUE TITLE
Required argument "color_by"

### ISSUE THREAD

**Issue by wward97** [boaz85/pymuller#1]
Hi! I was wondering what form this df should take? I poked through the code but could not figure out the inteded shape. It seems to need to have as index all the identities, but I am not sure what else.

**Comment by pablo-guridi** [comment]
Hello! I´ve been trying to use this package but also ran into trouble with this argument "color_by" that I was not expecting, did you manage to make it work? Thanks in advance!

**Comment by brettc** [comment]
I had the same problem. The `color_by` argument needs to be `pandas` series object where the index is the 'Identity' and the value is used to index into the colormap. This allows you to choose colors for all the Identities.

**Comment by boaz85** [comment]
Sorry for the late response. I didn't get any notification about this.

brettc is right. I'll add it to the readme.
