### ISSUE TITLE
More specific formatting instructions? getting an error when trying to plot

### ISSUE THREAD

**Issue by callaband** [boaz85/pymuller#2]
So I assigned all my strains a number, have estimated generation number (only 3 time points right now), and population is the number of individual samples of that strain at that time point. I made sure the dtypes were integers, but I am still getting an error that suggests that they are not. Have any recommendations?

![adjacency](https://user-images.githubusercontent.com/51763186/138732881-3a9c87a9-d3ae-4b35-a78c-29eae88936f8.png)
![populations](https://user-images.githubusercontent.com/51763186/138732888-c0e851c6-23b9-45b1-b3a8-b6594ccc020e.png)
![populations_dtypes](https://user-images.githubusercontent.com/51763186/138732890-4379c2db-87a7-47ef-bba7-df3d0dc5aeb5.png)
![error](https://user-images.githubusercontent.com/51763186/138732884-15d8d7c5-c5bc-4f29-a9f8-0c6b796a65f9.png)

**Comment by boaz85** [comment]
Hi,

You pass _ax_ as the first positional argument, but _muller_ expects the first argument to be _populations_df_.  
The right way to call it would be:

`muller(populations_df, adjacency_df, color_by, ax=ax)`
